# Generated by Django 5.2.17 on 2026-09-14 17:20

import core.models.user
import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('last_run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'job heartbeat',
                'verbose_name_plural': 'job heartbeats',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Institutional login ID supplied by the faculty roster.', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Institutional ID must not contain spaces.', regex='^\\S+$')], verbose_name='institutional ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='institutional email')),
                ('name_th', models.CharField(blank=True, max_length=200, verbose_name='Thai name')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='English name')),
                ('locale', models.CharField(choices=[('th', 'Thai'), ('en', 'English')], default='th', max_length=5, verbose_name='preferred language')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='email verified at')),
                ('eligibility', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16, verbose_name='eligibility')),
                ('eligibility_decided_at', models.DateTimeField(blank=True, null=True)),
                ('eligibility_reason', models.TextField(blank=True)),
                ('is_operational_staff', models.BooleanField(default=False, help_text='Members of the ten-account staff group; cannot grant superuser.', verbose_name='operational staff')),
                ('rules_ack_version', models.CharField(blank=True, max_length=32)),
                ('rules_ack_at', models.DateTimeField(blank=True, null=True)),
                ('eligibility_decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_decisions', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', core.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, help_text='Used for non-user actors such as the scheduler tick.', max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BookingControl',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'booking control',
                'verbose_name_plural': 'booking control',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='booking_control_singleton')],
            },
        ),
        migrations.CreateModel(
            name='CalendarOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date', models.DateField(unique=True)),
                ('is_open', models.BooleanField(default=False, help_text='Unchecked closes the whole day (holiday).')),
                ('open_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('close_hour', models.PositiveSmallIntegerField(blank=True, help_text='Exclusive end hour: the 20:00 close is stored as 20.', null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_overrides_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'calendar override',
                'verbose_name_plural': 'calendar overrides',
                'ordering': ['-local_date'],
            },
        ),
        migrations.CreateModel(
            name='EligibleStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutional_id', models.CharField(max_length=64, unique=True, verbose_name='institutional ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='approved email')),
                ('name_th', models.CharField(blank=True, max_length=200, verbose_name='Thai name')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='English name')),
                ('program', models.CharField(blank=True, max_length=120, verbose_name='programme')),
                ('instrument', models.CharField(blank=True, max_length=120, verbose_name='instrument')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('import_batch', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eligible student',
                'verbose_name_plural': 'eligible students',
                'ordering': ['institutional_id'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('purpose', models.CharField(choices=[('EMAIL_VERIFICATION', 'Email verification'), ('ACCOUNT_ACTIVATION', 'Account activation'), ('PASSWORD_RESET', 'Password reset')], max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=48)),
                ('language', models.CharField(default='th', max_length=5)),
                ('payload', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(max_length=191, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('EXHAUSTED', 'Exhausted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'operation request',
                'verbose_name_plural': 'operation requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('snapshot', models.JSONField()),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'policy version',
                'verbose_name_plural': 'policy versions',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='room number')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='label')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Display order.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ['position', 'number'],
                'indexes': [models.Index(fields=['is_active'], name='room_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('acknowledged_in_use', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures_created', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures_revoked', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, help_text='Leave empty to close every room.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closures', to='core.room')),
            ],
            options={
                'verbose_name': 'closure',
                'verbose_name_plural': 'closures',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_created', to=settings.AUTH_USER_MODEL)),
                ('rooms', models.ManyToManyField(blank=True, help_text='Leave empty to cover every room.', related_name='incidents', to='core.room')),
            ],
            options={
                'verbose_name': 'service incident',
                'verbose_name_plural': 'service incidents',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('slot_date', models.DateField(help_text='Bangkok local date of slot_start.')),
                ('deadline', models.DateTimeField(blank=True, help_text='Check-in deadline for an advance reservation; null for walk-ins.', null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_USE', 'In use'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No-show'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('source', models.CharField(choices=[('ADVANCE', 'Advance reservation'), ('WALK_IN', 'Walk-in / use now')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('late_cancel', models.BooleanField(default=False, help_text='Cancelled less than 60 minutes before the slot started (reporting only).')),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('completion_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellations_performed', to=settings.AUTH_USER_MODEL)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_performed', to=settings.AUTH_USER_MODEL)),
                ('original_no_show', models.ForeignKey(blank=True, help_text='The forfeited booking whose remaining time this walk-in took.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_ins_released', to='core.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('policy_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.policyversion')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.room')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.serviceincident')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-slot_start'],
            },
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, help_text='Required for automatic sanctions; null means an indefinite staff suspension.', null=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lift_reason', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('AUTO', 'Automatic (strike threshold)'), ('MANUAL', 'Staff decision')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_notified_at', models.DateTimeField(blank=True, null=True)),
                ('end_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_created', to=settings.AUTH_USER_MODEL)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_lifted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suspensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'suspension',
                'verbose_name_plural': 'suspensions',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NO_SHOW', 'No-show'), ('MANUAL', 'Recorded by staff')], max_length=16)),
                ('occurred_at', models.DateTimeField(help_text='When the violation happened: the check-in deadline for a no-show.')),
                ('expires_at', models.DateTimeField(help_text='End of the rolling strike window, frozen at recording time.')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('counts_as_strike', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations_recorded', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='core.booking')),
                ('consumed_by', models.ForeignKey(blank=True, help_text='The automatic suspension this strike triggered; set at most once.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_strikes', to='core.suspension')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='core.serviceincident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'violation',
                'verbose_name_plural': 'violations',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['eligibility'], name='user_eligibility_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('eligibility__in', ['PENDING', 'APPROVED', 'REJECTED'])), name='user_eligibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('locale__in', ['th', 'en'])), name='user_locale_valid'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='audit_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', 'occurred_at'], name='audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['occurred_at'], name='audit_occurred_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendaroverride',
            constraint=models.CheckConstraint(condition=models.Q(('is_open', False), models.Q(('open_hour__isnull', False), ('close_hour__isnull', False), ('close_hour__gt', models.F('open_hour'))), _connector='OR'), name='calendar_override_hours_consistent'),
        ),
        migrations.AddConstraint(
            model_name='calendaroverride',
            constraint=models.CheckConstraint(condition=models.Q(('open_hour__isnull', True), ('open_hour__lte', 23), _connector='OR'), name='calendar_override_open_hour_valid'),
        ),
        migrations.AddConstraint(
            model_name='calendaroverride',
            constraint=models.CheckConstraint(condition=models.Q(('close_hour__isnull', True), ('close_hour__lte', 24), _connector='OR'), name='calendar_override_close_hour_valid'),
        ),
        migrations.AddIndex(
            model_name='eligiblestudent',
            index=models.Index(fields=['is_active'], name='roster_active_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['expires_at'], name='invitation_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('user', 'purpose', 'generation'), name='invitation_user_purpose_generation_unique'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('token_digest',), name='invitation_token_digest_unique'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'next_attempt_at'], name='notif_due_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['lease_until'], name='notif_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SENT', 'EXHAUSTED', 'CANCELLED'])), name='notification_status_valid'),
        ),
        migrations.AddIndex(
            model_name='operationrequest',
            index=models.Index(fields=['created_at'], name='opreq_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationrequest',
            constraint=models.UniqueConstraint(fields=('user', 'operation', 'key'), name='operation_request_user_operation_key_unique'),
        ),
        migrations.AddIndex(
            model_name='closure',
            index=models.Index(fields=['starts_at', 'ends_at'], name='closure_bounds_idx'),
        ),
        migrations.AddIndex(
            model_name='closure',
            index=models.Index(fields=['room', 'starts_at'], name='closure_room_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='closure',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='closure_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='serviceincident',
            index=models.Index(fields=['starts_at', 'ends_at'], name='incident_bounds_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceincident',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='incident_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'slot_date'], name='booking_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'deadline'], name='booking_status_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'slot_end'], name='booking_status_end_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'slot_date'], name='booking_room_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'IN_USE', 'COMPLETED', 'NO_SHOW', 'CANCELLED'])), name='booking_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['ADVANCE', 'WALK_IN'])), name='booking_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('slot_end', django.db.models.expressions.CombinedExpression(models.F('slot_start'), '+', models.Value(datetime.timedelta(seconds=3600))))), name='booking_slot_length_one_hour'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('slot_start__minute', 0), ('slot_start__second', 0)), name='booking_slot_hour_aligned'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('source', 'ADVANCE'), models.Q(('status', 'SCHEDULED'), _negated=True), _connector='OR'), name='booking_walkin_never_scheduled'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deadline__isnull', False), ('source', 'ADVANCE')), models.Q(('deadline__isnull', True), ('source', 'WALK_IN')), _connector='OR'), name='booking_deadline_matches_source'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('checked_in_at__isnull', True), models.Q(('checked_in_at__gte', models.F('slot_start')), ('checked_in_at__lt', models.F('slot_end'))), _connector='OR'), name='booking_checkin_within_slot'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('status', 'CANCELLED')), models.Q(models.Q(('status', 'CANCELLED'), _negated=True), ('cancelled_at__isnull', True)), _connector='OR'), name='booking_cancellation_requires_metadata'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('cancel_reason', ''), ('cancelled_at__isnull', False), _connector='OR'), name='booking_cancel_reason_requires_cancellation'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'IN_USE', 'COMPLETED'])), fields=('room', 'slot_start'), name='booking_room_slot_unique'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'IN_USE', 'COMPLETED'])), fields=('user', 'slot_start'), name='booking_user_slot_unique'),
        ),
        migrations.AddIndex(
            model_name='suspension',
            index=models.Index(fields=['user', 'ends_at'], name='suspension_user_end_idx'),
        ),
        migrations.AddIndex(
            model_name='suspension',
            index=models.Index(fields=['lifted_at'], name='suspension_lifted_idx'),
        ),
        migrations.AddConstraint(
            model_name='suspension',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['AUTO', 'MANUAL'])), name='suspension_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='suspension',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='suspension_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='suspension',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'AUTO'), _negated=True), ('ends_at__isnull', False), _connector='OR'), name='suspension_auto_requires_end'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['user', 'expires_at'], name='violation_user_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['user', 'consumed_by'], name='violation_consumed_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['occurred_at'], name='violation_occurred_idx'),
        ),
        migrations.AddConstraint(
            model_name='violation',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['NO_SHOW', 'MANUAL'])), name='violation_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='violation',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('occurred_at'))), name='violation_expiry_after_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='violation',
            constraint=models.CheckConstraint(condition=models.Q(('voided_at__isnull', False), ('void_reason', ''), _connector='OR'), name='violation_void_reason_requires_void'),
        ),
        migrations.AddConstraint(
            model_name='violation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'NO_SHOW'), _negated=True), ('booking__isnull', False), _connector='OR'), name='violation_no_show_requires_booking'),
        ),
        migrations.AddConstraint(
            model_name='violation',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'NO_SHOW')), fields=('booking',), name='violation_no_show_unique_per_booking'),
        ),
    ]
