# Generated by Django 5.2.17 on 2026-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_booking_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Pending on-site intervention by staff.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='review_note',
            field=models.TextField(blank=True),
        ),
    ]
