# Generated by Django 5.2.17 on 2026-09-15 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_needs_review_booking_review_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligiblestudent',
            name='instrument_category',
            field=models.CharField(choices=[('PIANO', 'Piano'), ('PERCUSSION', 'Percussion'), ('STRINGS', 'Strings'), ('WOODWIND', 'Woodwind'), ('BRASS', 'Brass'), ('VOICE', 'Voice'), ('GUITAR', 'Guitar'), ('HARP', 'Harp'), ('OTHER', 'Other'), ('UNKNOWN', 'Not yet categorised')], default='UNKNOWN', help_text='Canonical family derived from the instrument text; drives room audiences.', max_length=32, verbose_name='instrument category'),
        ),
        migrations.AddField(
            model_name='room',
            name='reservation_scope',
            field=models.CharField(choices=[('EVERYONE', 'Any eligible student'), ('LISTED', 'Only the instrument categories listed')], default='EVERYONE', max_length=16, verbose_name='who may reserve'),
        ),
        migrations.CreateModel(
            name='RoomAllowedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PIANO', 'Piano'), ('PERCUSSION', 'Percussion'), ('STRINGS', 'Strings'), ('WOODWIND', 'Woodwind'), ('BRASS', 'Brass'), ('VOICE', 'Voice'), ('GUITAR', 'Guitar'), ('HARP', 'Harp'), ('OTHER', 'Other'), ('UNKNOWN', 'Not yet categorised')], max_length=32)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_categories', to='core.room')),
            ],
            options={
                'verbose_name': 'room instrument category',
                'verbose_name_plural': 'room instrument categories',
                'constraints': [models.UniqueConstraint(fields=('room', 'category'), name='room_allowed_category_unique')],
            },
        ),
    ]
