# Generated by Django 5.2.17 on 2026-09-19 03:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backfill_instrument_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_hour', models.PositiveSmallIntegerField(help_text='Inclusive, e.g. 10 for 10:00.')),
                ('end_hour', models.PositiveSmallIntegerField(help_text='Exclusive end hour: 12 means the block ends at 12:00.')),
                ('reason', models.CharField(help_text='Shown to students, e.g. the course name.', max_length=200)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Inclusive; empty means no end.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_blocks', to='core.room')),
            ],
            options={
                'verbose_name': 'weekly room block',
                'verbose_name_plural': 'weekly room blocks',
                'ordering': ['room', 'weekday', 'start_hour'],
                'indexes': [models.Index(fields=['room', 'weekday'], name='weekly_block_room_day_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_hour__gt', models.F('start_hour'))), name='weekly_block_end_after_start'), models.CheckConstraint(condition=models.Q(('end_hour__lte', 24)), name='weekly_block_hours_valid'), models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='weekly_block_validity_window'), models.UniqueConstraint(fields=('room', 'weekday', 'start_hour'), name='weekly_block_room_day_hour_unique')],
            },
        ),
    ]
