# Generated by Django 5.2.17 on 2026-09-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_weeklyblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='declared_category',
            field=models.CharField(blank=True, choices=[('PIANO', 'Piano'), ('PERCUSSION', 'Percussion'), ('STRINGS', 'Strings'), ('WOODWIND', 'Woodwind'), ('BRASS', 'Brass'), ('VOICE', 'Voice'), ('GUITAR', 'Guitar'), ('HARP', 'Harp'), ('OTHER', 'Other'), ('UNKNOWN', 'Not yet categorised')], help_text='The instrument family the student declared at registration. A roster link, when it exists, is authoritative over this value.', max_length=32, verbose_name='declared instrument'),
        ),
    ]
