# Generated by Django 5.2.17 on 2026-09-19 04:55

import secrets

from django.db import migrations, models


def backfill_tokens(apps, schema_editor):
    """Every advance reservation gets its QR check-in token (D-31)."""
    Booking = apps.get_model("core", "Booking")
    for booking in Booking.objects.filter(checkin_token__isnull=True).iterator():
        booking.checkin_token = secrets.token_urlsafe(24)
        booking.save(update_fields=["checkin_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_declared_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='check-in token'),
        ),
        migrations.RunPython(backfill_tokens, migrations.RunPython.noop),
    ]
