# Generated by Django 5.2.17 on 2026-09-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_booking_checkin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Faculty account. Read-only today; permissions widen later.', verbose_name='teacher'),
        ),
    ]
