# Generated by Django 5.2.17 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_user_is_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="details_version",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="participant_names",
            field=models.TextField(blank=True, help_text="Optional names of other participants.", max_length=500),
        ),
        migrations.AddField(
            model_name="booking",
            name="purpose",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="booking",
            name="title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="room",
            name="capacity",
            field=models.PositiveSmallIntegerField(default=1, help_text="Approximate number of people the room can accommodate."),
        ),
        migrations.AddField(
            model_name="room",
            name="equipment",
            field=models.TextField(blank=True, help_text="Comma-separated equipment or facilities available in this room."),
        ),
    ]
