# Generated by Django 5.2.17 on 2026-09-20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_priority_two_details_and_room_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_hour", models.PositiveSmallIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("title", models.CharField(blank=True, max_length=120)),
                ("purpose", models.TextField(blank=True, max_length=500)),
                ("participant_names", models.TextField(blank=True, max_length=500)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("CANCELLED", "Cancelled")], default="ACTIVE", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=False, default=django.utils.timezone.now)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recurring_reservations", to="core.room")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recurring_reservations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="recurring_user_status_idx"),
                    models.Index(fields=["room", "start_date"], name="recurring_room_start_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recurringreservation",
            constraint=models.CheckConstraint(condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)), name="recurring_weekday_valid"),
        ),
        migrations.AddConstraint(
            model_name="recurringreservation",
            constraint=models.CheckConstraint(condition=models.Q(("start_hour__gte", 0), ("start_hour__lte", 23)), name="recurring_start_hour_valid"),
        ),
        migrations.AddConstraint(
            model_name="recurringreservation",
            constraint=models.CheckConstraint(condition=models.Q(("end_date__gte", models.F("start_date"))), name="recurring_date_range_valid"),
        ),
        migrations.AddConstraint(
            model_name="recurringreservation",
            constraint=models.CheckConstraint(condition=models.Q(status__in=["ACTIVE", "CANCELLED"]), name="recurring_status_valid"),
        ),
        migrations.CreateModel(
            name="RoomAdministrator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=False, default=django.utils.timezone.now)),
                ("granted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="room_administrator_grants", to=settings.AUTH_USER_MODEL)),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="administrators", to="core.room")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="room_administrations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["room", "user"],
            },
        ),
        migrations.AddConstraint(
            model_name="roomadministrator",
            constraint=models.UniqueConstraint(fields=("room", "user"), name="room_admin_unique"),
        ),
        migrations.AddField(
            model_name="room",
            name="requires_approval",
            field=models.BooleanField(default=False, help_text="Reservations for this room must be approved by a room administrator."),
        ),
        migrations.AddField(
            model_name="booking",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="booking_approvals", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="booking",
            name="approval_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="recurrence",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="occurrences", to="core.recurringreservation"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_APPROVAL", "Awaiting room approval"),
                    ("SCHEDULED", "Scheduled"),
                    ("IN_USE", "In use"),
                    ("COMPLETED", "Completed"),
                    ("NO_SHOW", "No-show"),
                    ("CANCELLED", "Cancelled"),
                    ("REJECTED", "Not approved"),
                ],
                max_length=16,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="booking_status_valid",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(status__in=["PENDING_APPROVAL", "SCHEDULED", "IN_USE", "COMPLETED", "NO_SHOW", "CANCELLED", "REJECTED"]),
                name="booking_status_valid",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="booking_room_slot_unique",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(status__in=["PENDING_APPROVAL", "SCHEDULED", "IN_USE", "COMPLETED"]),
                fields=("room", "slot_start"),
                name="booking_room_slot_unique",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="booking",
            name="booking_user_slot_unique",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(status__in=["PENDING_APPROVAL", "SCHEDULED", "IN_USE", "COMPLETED"]),
                fields=("user", "slot_start"),
                name="booking_user_slot_unique",
            ),
        ),
    ]
